= DRVO
Dit zijn de stappen en het resultaaat die ik heb gevold voor het vak driver ontwikkeling

== H2 Character device driver

=== H2.2

dit is mijn .c file die ik gebruikt hebt
[,.c]
----
include::src/hello.c[]
----

=== H2.3

waneer ik dit commando run met de meegegeven Makefile dan krijg ik het resultaat.
[.terminal]
----
make hello.ko obj-m=hello.o -C /lib/modules/4.15.0-54-generic/build M=/home/joan/drvo/
modules
----

resultaat:
[.terminal]
----
niels@niels-virtual-machine:~/github/DRVO/src$ make
make -C /lib/modules/6.5.0-28-generic/build M=/home/niels/github/DRVO/src modules
make[1]: Entering directory '/usr/src/linux-headers-6.5.0-28-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /home/niels/github/DRVO/src/hello.o
  MODPOST /home/niels/github/DRVO/src/Module.symvers
  CC [M]  /home/niels/github/DRVO/src/hello.mod.o
  LD [M]  /home/niels/github/DRVO/src/hello.ko
  BTF [M] /home/niels/github/DRVO/src/hello.ko
Skipping BTF generation for /home/niels/github/DRVO/src/hello.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-28-generic'

----

ik krijg wat warnings maar kan het bouwen en testen.

=== H2.4

Als eerste heb ik in een andere terminal de commando:
[.terminal]
----
sudo dmesg -w
----
Om ervoor te zorgen dat ik printk kan meekijken.


Dan doe ik het commando:
[.terminal]
----
sudo insmod hello.ko
----

En krijg ik het resultaat in de log te zien:
[.terminal]
----
[ 5280.572849] Hello, world
----

En wanneer ik het commando:
[.terminal]
----
sudo rmmod hello
----

krijg het resultaat te zien in de log:
[.terminal]
----
[ 5362.805165] Goodbye, world
----

== 3 Bouw een standaard device driver

=== H3.1

.dit is mijn opgave 3.1.c file:

.source code:
[.c]
----
include::src/opgave_3_1.c[]
----

.Commando om te bouwen:
[.terminal]
----
make
----
.Kernel resultaat bij registeren en de-registreren:
[.terminal]
----
[ 6537.263969] Hello, world
[ 6539.340526] Goodbye, world
----
.Dat de module in /proc/modules staat als de module geregistreerd is:
[.terminal]
----
niels@niels-virtual-machine:~/github/DRVO$ cat /proc/modules
hello 12288 0 - Live 0x0000000000000000 (OE)
tls 151552 0 - Live 0x0000000000000000
isofs 61440 2 - Live 0x0000000000000000
vsock_loopback 12288 0 - Live 0x0000000000000000
vmw_vsock_virtio_transport_common 57344 1 vsock_loopback, Live 0x0000000000000000
intel_rapl_msr 20480 0 - Live 0x0000000000000000
vmw_vsock_vmci_transport 45056 1 - Live 0x0000000000000000
vsock 61440 5 vsock_loopback,vmw_vsock_virtio_transport_common,vmw_vsock_vmci_transport, Live 0x0000000000000000
intel_rapl_common 40960 1 intel_rapl_msr, Live 0x0000000000000000
vmw_balloon 28672 0 - Live 0x0000000000000000
----
.Dat de module staat in lsmod als de module geregistreerd is:
[.terminal]
----
niels@niels-virtual-machine:~/github/DRVO/src$ sudo lsmod
Module                  Size  Used by
hello                  12288  0
tls                   151552  0
isofs                  61440  2
----

=== H3.2
[.Makefile]
----
include::src/Makefile[]
----

=== H3.3
[.terminal]
----
include::src/build_log_opgave3_3.txt[]
----

=== H4.3



